version: "3.8"

services:



  backend:
    build:
      context: ./backend
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=inkwell
    depends_on:
      mysql:
        condition: service_healthy   



  frontend:
    build:
      context: ./frontend
    ports:
      - "${VITE_FRONTEND_PORT}:5173"
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:  ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env

volumes:
  mysql-data: